### ISSUE TITLE
Put changelog after articles section?

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#105]
Just a matter of taste, I just think articles are more important for most users

I mean this for the default template, not just for the altdoc website

**Comment by vincentarelbundock** [comment]
Yes, totally agree.

**Comment by vincentarelbundock** [comment]
maybe also after reference, just because those are the two foldable sections, but I'm less sure about this.

**Comment by vincentarelbundock** [comment]
Should we change "Articles:" to "Vignettes:"?

**Comment by etiennebacher** [comment]
> Should we change "Articles:" to "Vignettes:"?

I'd rather not, not all articles have to be vignettes included in the package, right?
