### ISSUE TITLE
`mkdocs` needs the yaml file to be a parent of the `docs` folder

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#116]
Not possible to store `mkdocs.yml` and the documentation files in `docs`. Either the yaml file must be at the root of the package, or the documentation files must be in "docs/docs".

For now, we have: 
```
ERROR -  Config value 'docs_dir': The path 'C:\Users\etienne\Desktop\Divers\WDI\docs\docs' isn't 
        an existing directory.
```

If we change the `docs_dir` to be `'.'` i.e the same directory as where the yaml file is, then we have:
```
ERROR    -  Config value 'docs_dir': The 'docs_dir' should not be the parent directory of the config file. Use 
          a child directory instead so that the 'docs_dir' is a sibling of the config file.
```

**Comment by vincentarelbundock** [comment]
Quarto is also like that: We need to build from a different directory and then move the results if we want to re-build manually or use any of the extra functionality like "freeze". In my Quarto PR (now merged), I created a new directory called `_quarto` in the top level, and added it to both `.Rbuildignore` and `.gitignore`. I propose we do the same thing with MkDocs:

1. Leave the process as is for building: Create a `mkdocs.yml` file in the root directory.
2. Do *not* clean up that settings file on exit, but add it to `.Rbuildignore` and `.gitignore`.
3. Document this in roxygen2 to say that this file is (1) a byproduct of the build process, (2) overwritten every time users run `render_docs()`, and (3) left there to allow users to build the site manually by calling `mkdocs build` directly.

**Comment by etiennebacher** [comment]
2. If we put it in .gitignore, then it will never appear on the `main` branch, which means that Github Pages (for example) has to be deployed from another branch

3. In addition to the info in roxygen2 we could add a note at the top of `./mkdocs.yml` (not `altdoc/mkdocs.yml`) such as `# Generated by altdoc: do not edit by hand` (this is what roxygen2 puts at the top of NAMESPACE)

**Comment by vincentarelbundock** [comment]
> 2. If we put it in .gitignore, then it will never appear on the `main` branch, which means that Github Pages (for example) has to be deployed from another branch

No, because the top level `mkdocs.yml` is not actually required to view the website. Currently, the fully rendered website is properly moved to `docs/` and can be deployed to Github Pages using the normal workflow. The top level `mkdocs.yml` is *only* used if a user wants to manually call `mkdocs build` from the command line. It serves no other purpose (and frankly, I'm not even sure we should keep it; I'm just proposing this in reaction to your puzzlement). The only code that changes line line where we `fs::file_delete` the file at the very end of the process.


> 3. In addition to the info in roxygen2 we could add a note at the top of `./mkdocs.yml` (not `altdoc/mkdocs.yml`) such as `# Generated by altdoc: do not edit by hand` (this is what roxygen2 puts at the top of NAMESPACE)

Good idea.

**Comment by etiennebacher** [comment]
> No, because the top level mkdocs.yml is not actually required to view the website

Indeed, forgot about that

> The top level mkdocs.yml is only used if a user wants to manually call mkdocs build from the command line

I reported this error because `setup_docs("mkdocs")` + `render_docs()` doesn't work for me. `render_docs()` calls `mkdocs` so it generates an error if `mkdocs.yml` isn't there.

**Comment by vincentarelbundock** [comment]
What specific error do you get when you run this in the `altdoc` repo?

```r
library(altdoc)
setup_docs("mkdocs", overwrite = TRUE)
render_docs()
```

**Comment by etiennebacher** [comment]
Ah no sorry it's `altdoc::preview_docs()` that fails because `mkdocs.yml` is in `docs` and it calls `mkdocs serve`. Since `index.html` is in `docs`, we can just call `servr::httw()`, just like for docute and docsify. 

Bottom line, we can remove `mkdocs.yml` once `render_docs()` has finished, and we can remove the if condition for `mkdocs` in `preview_docs()`

**Comment by etiennebacher** [comment]
Yes I will
