### ISSUE TITLE
Remove `reformat_md()`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#123]
In general, I don't like it when software changes my files. Why don't we do this:

1. Remove `reformat_md()`
2. Document the recommended README structure on the website and in the man pages.
3. Print an informative warning when users build non-conforming websites.

This would also simplify the code on the back end and remove the need for `tinkr` (which doesn't seem widely used, and depends on a bunch of things going up to Rcpp and friends).

**Comment by vincentarelbundock** [comment]
I'm thinking about something very simple like:

```r
warn_level_1_headers <- function(file_path) {
  file_path <- "vignettes/get-started.Rmd"
  content <- .readlines(file_path)
  idx <- grep("^```", content)

  # backticks are incorrectly paired. We don't know what to do.
  if (length(idx) %% 2 != 0) {
    return(invisible())
  }

  # drop code blocks
  backtick_pairs <- rev(split(idx, ceiling(seq_along(idx) / 2)))
  for (p in backtick_pairs) {
    content[p[1]:p[2]] <- NA
  }
  content <- stats::na.omit(content)

  # too many level 1 header
  if (isTRUE(sum(grepl("^# ", content)) > 1)) {
    cli::cli_alert_danger("Too many level 1 headings in {.file basename(file_path)}. {.code altdoc} assumes that the only level 1 heading is the title of the document. All other subheadings should be at least level, starting with: {.code ##}")
  }
}
```

**Comment by etiennebacher** [comment]
Sounds good to me, but why is there a check for backticks? After all that would also mean a rendering problem on github so not sure we should take this into account

**Comment by vincentarelbundock** [comment]
We want to raise a warning if there is more than one level 1 header in the file. 

But code chunks could have comments that look like level 1 headers and would this raise a warning. So we first drop all code chunks, then check if there is more than one level 1 header.

**Comment by etiennebacher** [comment]
Oh, right I had forgot about that
