### ISSUE TITLE
CHANGELOG vs. NEWS

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#133]
Some packages have both a CHANGELOG and a NEWS. The former is more similar to a git log, with info about most commits. The latter announces the main features of a release. I propose:

* Support both types of files simultaneously.
* In the sidebar, use a label which corresponds to the file name. If the user uses a NEWS file, then the sidebar should show "News" instead of "Changelog"

**Comment by etiennebacher** [comment]
So just to clarify, when there are both news and changelog, do you want to show both on the website? or just NEWS and label it "News"?

**Comment by vincentarelbundock** [comment]
Yes show both on the website as separate items in the sidebar. I imagine this is a corner case anyway, so it won't matter.

The only real change here in most cases is that we would call NEWS "news" instead of calling it (arguably incorrectly) "changelog"

**Comment by etiennebacher** [comment]
Ok, fine for me
