### ISSUE TITLE
Freeze parallel bug

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#142]
Maybe a problem here. Not sure I can reproduce right now.

```r
Error in ...future.FUN(...future.X_jj, ...) : 
  unused argument (freeze = FALSE)
```

**Comment by etiennebacher** [comment]
Should have been fixed in #122: https://github.com/etiennebacher/altdoc/pull/122/commits/7c1b0f768fd490a649a293b992837c34b0eedac6
