### ISSUE TITLE
Exclude `keywords{internal}` from the sidebar

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#148]
We probably still want to convert `.Rd` files anyway,in case the user does want to display them, they can add the files manually.

**Comment by etiennebacher** [comment]
Hum, I'm not sure about this. In packages that make extensive use of `@keywords internal`, that might slow down the process quite a bit, even if the user doesn't want to include them. Isn't there a way to handle those with pre-/post-processing?

(I haven't played yet with those pre-processing or post-processing steps, I intend to try more on `polars` tomorrow)

**Comment by vincentarelbundock** [comment]
Sounds good. I'm also playing around with more complicated websites and notice that there are still many problems with the auto-generated images in vignettes in and the freeze functionality. This is still pretty far from release-ready, I think.

**Comment by vincentarelbundock** [comment]
fixed here: https://github.com/etiennebacher/altdoc/pull/151
