### ISSUE TITLE
GHA problem

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#158]
I get an error when I tried GHA with marginaleffects:

https://github.com/vincentarelbundock/marginaleffects/actions/runs/6990619047

**Comment by etiennebacher** [comment]
You have `altdoc:` in your yaml while it should be `jobs: altdoc:`

**Comment by etiennebacher** [comment]
Looks like it's an error in our template

**Comment by etiennebacher** [comment]
Fixed in [2004353](https://github.com/etiennebacher/altdoc/commit/2004353cb2c34dc8b98059084db20d77d84ac4c6)

**Comment by vincentarelbundock** [comment]
Another one:

https://github.com/vincentarelbundock/marginaleffects/actions/runs/6990740332

> [altdoc](https://github.com/vincentarelbundock/marginaleffects/actions/runs/6990740332/job/19020987406)
> Canceling since a deadlock for concurrency group 'altdoc-true' was detected between 'top level workflow' and 'altdoc'

**Comment by etiennebacher** [comment]
Can you try again with the latest commit on `main`?

**Comment by vincentarelbundock** [comment]
When I commented out the concurrency , I got this: 

> [altdoc](https://github.com/vincentarelbundock/marginaleffects/actions/runs/6990979734/job/19021039836#step:9:24)
'render_docs' is not an exported object from 'namespace:altdoc'

Probably need to install the dev version.

Also, it takes forever to install the dependencies. I guess we're not using r2u after all?

**Comment by etiennebacher** [comment]
> Probably need to install the dev version.

Yes, you need `etiennebacher/altdoc` in Remotes. 

> Also, it takes forever to install the dependencies. I guess we're not using r2u after all?

I think I got confused between r2u and the other scripts of Dirk. I added back his scripts in #159, I'll merge if it works

**Comment by etiennebacher** [comment]
Looks good, can you try again with latest dev version?

**Comment by vincentarelbundock** [comment]
Off th computer for the weekend. But yeah, r2u is an apt-get repository with all the CRAN packages

**Comment by vincentarelbundock** [comment]
I think we need to load future for `parallel=TRUE` to work

**Comment by vincentarelbundock** [comment]
The file in `inst/` is not updated, so `setup_github_actions()` installs the wrong workflow

**Comment by vincentarelbundock** [comment]
MkDocs and material are missing from the workflow.

**Comment by vincentarelbundock** [comment]
Until we release the new version to CRAN this is necessary:

```bash
      - name: Altdoc dev version
        run: ./run.sh install_github etiennebacher/altdoc
```

**Comment by etiennebacher** [comment]
> Until we release the new version to CRAN this is necessary:

In the r-polars PR where I prepare for altdoc 0.3.0, just using `etiennebacher/altdoc` in the `DESCRIPTION` was enough
