### ISSUE TITLE
Merge r2readthedocs and altdoc

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#19]
Add two functionalities of [r2readthedocs](https://github.com/ropenscilabs/r2readthedocs) in altdoc:
* use [sphinx](https://www.sphinx-doc.org/en/master/) documentation generator
* add option to pull the documentation from package dependencies to have a self-contained website (e.g [ropensci-review-tools](https://ropensci-review-tools.readthedocs.io/en/latest/))

@mpadge Feel free to add anything you want about the merge process here: potential issues, functionalities that I forgot to mention, etc.

**Comment by vincentarelbundock** [comment]
AFAICT, this uses restructuredtext, so it's quite a bit different than the Markdown/Quarto based generators we currently use. It's likely to require a very different infrastructure. 

Are there very compelling reasons to prefer this over our current generators?

If not, I'd close this as out of scope.

**Comment by mpadge** [comment]
Yes, `r2readthedocs` is indeed all based on `.rst`, so not compatible with quarto in current form. I'm happy for this to be closed for now, but will keep an eye on `altdoc` developments. Thanks!
