### ISSUE TITLE
Quarto doesn't work well

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#200]
+ [x] warning tries to import preamble but we don't use them for Quarto. We probably want to use them, no?
+ [ ] import_vignettes() breaks when there is only 1 vignette
+ [ ] too many nesting levels and duplicated files. Just build in `_quarto` directly. But maybe we need that for relative links to work properly?
+ [ ] `freeze=TRUE` doesn't seem to make a difference

I'll look into all this.

**Comment by etiennebacher** [comment]
Hi @vincentarelbundock, I'd like to submit 0.3.0 to CRAN before their break (22 Dec. - 8 Jan.). Releasing 0.3.0 will allow me to merge the corresponding PR in polars, which is currently blocking other documentation issues.

Do you think those issues could be fixed before that? I still have a few things to do, like #212 and more testing

**Comment by vincentarelbundock** [comment]
Hmmm, possibly, but it's end of semester and Christmas craziness, and I have a paper to finish with fixed deadline.

Also, it feels like every time I try this on a new repo I discover new issues. I personally think it would be better to wait a bit and release a robust 0.3.0 which we could proudly recommend.

Why can't you use the dev version for polars by installing it from Config: in DESCRIPTION?

**Comment by etiennebacher** [comment]
> Why can't you use the dev version for polars by installing it from Config: in DESCRIPTION?

Precisely because the dev version changes often, but I guess I can pin it to a particular commit.

**Comment by vincentarelbundock** [comment]
I know it's annoying, but I guess this proves the point. We don't want to release something that still moves so much it's unusable...

**Comment by vincentarelbundock** [comment]
https://github.com/etiennebacher/altdoc/pull/240
