### ISSUE TITLE
PDF vignettes

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#226]
+ [ ] Docute always adds '.md' to the link, even if there is already a `.pdf` extension.
+ [ ]  Test Quarto

**Comment by etiennebacher** [comment]
The easiest way to make this work for all doc generators would probably be to have a section "Additional vignettes" in the sidebar that contains links to the files on the github repo.

I don't see anything in the docute docs on how to include a PDF file

**Comment by vincentarelbundock** [comment]
Right, so it works now with the thing I've merged yesterday. No need for a new section, they just are in vignettes and users can customize the sidebar as usual if they want them separate.

Maybe we just document this doesn't work in Docute.

**Comment by etiennebacher** [comment]
Yes, sounds good. I will add a mini pdf in the test package used in snapshot tests so I can update the documentation at the same time

**Comment by etiennebacher** [comment]
Done. Not closing this because I don't know if you already tested with quarto

**Comment by vincentarelbundock** [comment]
https://github.com/etiennebacher/altdoc/pull/240
