### ISSUE TITLE
Make `render_docs()` error if there are any rendering failures

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#238]
I think it's good that we delay the error until the end of `render_docs()` so that we can get the full list of failures, but in the end there should be an error.

For example, this workflow has plenty of failures but I had no idea: https://github.com/pola-rs/r-polars/actions/runs/7251398268/job/19753670691#step:10:258

**Comment by vincentarelbundock** [comment]
Not sure what the use case is, but counterpoint: My build takes 20 minutes. I like to see errors before the end if possible.

That said, I don't have super strong feelings about this.

**Comment by etiennebacher** [comment]
We can also error early. The thing is that since my build takes around 15min I rarely run the whole thing locally and rely on the CI. When this is the case I want to see if multiple things failed so I can fix everything at once and avoid several push-and-wait-for-ci cycles. Could be an option `fail_early = FALSE/TRUE`?

In any case we should throw an error

**Comment by vincentarelbundock** [comment]
Nah, I think that's a really niche decision and not an important one. Just pick the default you want.

As long as I can do `verbose=TRUE` and monitor along the way, it should be fine.

Thanks!
