### ISSUE TITLE
Switch to R Markdown for man pages?

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#242]
Rendering dozens of qmd files takes a lot of time because `altdoc` calls one quarto process per document, which takes 2-5 seconds. This mostly is a problem in `polars` where the update in `altdoc` increased the docs CI from ~4 min to ~12 min, even with parallel rendering.

It makes sense to use quarto for vignettes because users might mix qmd and Rmd files, but for man pages I wonder if using R Markdown wouldn't be sufficient. IIRC the only case when we need to use quarto for man pages is when the user builds a quarto website. If we know that the tool used is not `"quarto_website"` then we can switch to R Markdown.

**Comment by etiennebacher** [comment]
For now I'm mostly focused on having something robust and that works, though

**Comment by vincentarelbundock** [comment]
I don't know what code change this would involve. If you want to add an option, I guess that's fine, but removing quarto rendering would be a disappointing change. 

Also, isn't that what freeze is for? Rendering polars should take no more than a minute with freeze. Build it once a month from scratch, and with freeze on a daily basis.

**Comment by eitsupi** [comment]
I'm not sure, is there something wrong with using Rmd in all cases since Quarto CLI can render Rmd files?

**Comment by etiennebacher** [comment]
The problem was not using Rmd or qmd files but rather that Quarto is slower than R Markdown when rendering many files  (in my experience from 1 year ago, this might have changed). But I think it's unlikely that we change the tooling now, it's probably better to rely on better features from Quarto, e.g. https://github.com/quarto-dev/quarto-cli/issues/6116#issuecomment-1623392731
