### ISSUE TITLE
[notabug] How to fix R BATCH so that tests work?

### ISSUE THREAD

**Issue by barracuda156** [etiennebacher/altdoc#254]
There is some issue with `R` in Macports, apparently affecting only R BATCH, which causes tests to fail with some packages, including `altdoc`. _This is not your bug, this is our bug,_ I believe.

But maybe someone could advise me how to fix this?

```
* checking tests ...
  Running ‘spelling.R’
  Running ‘testthat.R’/opt/local/Library/Frameworks/R.framework/Resources/bin/BATCH: line 60: 35377 Illegal instruction     ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1

 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(altdoc)
  > 
  > test_check("altdoc")
  v Setting active project to '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-altdoc/R-altdoc/work/.tmp/Rtmp66sUly/testpkg8a312400570'
  i Creating `altdoc/` directory.
  i Creating `docs/` directory.
  i Adding ^docs$ to .Rbuildignore
  i Adding ^altdoc$ to .Rbuildignore
  i Adding altdoc/freeze.rds to .gitignore
  i Importing default settings file(s) to `altdoc/`
* DONE

Status: 1 ERROR, 1 NOTE
See
  ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-altdoc/R-altdoc/work/altdoc-a707901a2e74b9fd090809b168b01c3757229d61/altdoc.Rcheck/00check.log’
for details.

Command failed: /opt/local/bin/R CMD check ./altdoc_0.2.2.9014.tar.gz --no-manual --no-build-vignettes
Exit code: 1
```

I got the same error with several packages, and on different architectures with different compilers. I think the issue is with `R` itself, and likely specifically in Macports.
See also: https://trac.macports.org/ticket/67059

**Comment by etiennebacher** [comment]
Sorry, I have no clue about this. I don't know what R BATCH is, and I don't have a Mac so I can't explore this more deeply. The Github actions on macOS are passing and I don't see any other error message in what you report above.

**Comment by vincentarelbundock** [comment]
Closing as I don't think anyone but Etienne and I monitor this repository, and neither of us know about this.

Also, not altdoc specific.

**Comment by barracuda156** [comment]
Got it, thank you.
