### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#255]
Feels like dev activity has slowed down a bit. Do you want to think about a CRAN release soon?

**Comment by vincentarelbundock** [comment]
Yes, I think it would be useful.

Also, I put a lot of time into it already and feel it would be a shame to not let other people benefit from it.

I understand you don't have time for this, but I do, and I'm happy to basically maintain this and fix bugs for the foreseeable future.

**Comment by etiennebacher** [comment]
Cool, I'll try to make a new release in the next few days then

**Comment by etiennebacher** [comment]
@vincentarelbundock it's on CRAN now (binaries not built yet)

Btw I forgot to include it in #256 but feel free to replace `ctb` by `aut` in the DESCRIPTION

**Comment by vincentarelbundock** [comment]
Wonderful! Thanks a ton for your time on this!
