### ISSUE TITLE
plot2 -> tinyplot

### ISSUE THREAD

**Issue by eddelbuettel** [etiennebacher/altdoc#258]
@grantmcdermott renamed the package from `plot2` to `tinyplot` but didn't put stubs for `plot2` on his website so the links are currently borked.  I'd edit it in place but because you have two READMEs it may be better if I leave it to you.

**Comment by etiennebacher** [comment]
Thanks, should be fixed in [da02933](https://github.com/etiennebacher/altdoc/commit/da0293311cf0fa0abb90d499c41b2dc7bf30204b)

**Comment by eddelbuettel** [comment]
This man is faster than the speed of light :)

**Comment by grantmcdermott** [comment]
> didn't put stubs for plot2

Wait, what should I have done?

**Comment by eddelbuettel** [comment]
The URL https://grantmcdermott.com/plot2 was once valid and promoted as the package existed for a few months and nobody was too shy about it.  You could have (and I stress 'could', I am not being normative here) added a webserver redirect (or, my personal fave on local sites) a softlink.    But you didn't.  So when I followed along the docs from @vincentarelbundock 's toot earlier I hit the dreaded 404.  Oh well.

Issue files, and Etienne, faster than superman himself, fixed it already.  Now I guess it is a matter of rolling that fix to where it needs to be and/or you bribing your kids by giving them a cookie for every `plot2` URL they find in the wild.

Didn't someone say naming was hard?  Try renaming...

**Comment by etiennebacher** [comment]
> Also, still seems to be wrong on the actual altdoc [website](https://altdoc.etiennebacher.com/#/#demos)

Indeed, that should be fixed now but I had to patch it manually because the README.md file was not pushed automatically to `gh-pages` branch. I'll open a new issue for that, nice catch

**Comment by grantmcdermott** [comment]
Ah, good callout. I'll add a redirect softlink when I get a sec. Also need to do this for another renamed package. 😬

**Comment by eddelbuettel** [comment]
We are fighting the good fight of combatting link rot, one `ln -s` at a time!
