### ISSUE TITLE
Quarto website not copied to `docs/`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#264]
@kylebutts with the refactor, I think that the built website no longer gets copied over to `docs/`. I get the fully built website in `_quarto/_site` with freeze feature, but we also want it to be deployed in `docs/`, because that is where Github actions deploys from.

**Comment by vincentarelbundock** [comment]
Side note: we can't delete all files in `docs/` before copying because it includes things like `CNAME` that github put there once but won't re-generate.

**Comment by kylebutts** [comment]
@vincentarelbundock That's the breaking change. You need to add this to you quarto_website.yml
```
project:
  output-dir: ../docs/
```

**Comment by vincentarelbundock** [comment]
yep yep. I just didn't completely missed the boat on the whole conversation we had earlier. 

Thanks!
