### ISSUE TITLE
`.gitignore` expression for `freeze` of Quarto

### ISSUE THREAD

**Issue by kazuyanagimoto** [etiennebacher/altdoc#268]
Hi. I think the package currently produces the following expression in `.gitignore` for `freeze = TRUE` in Quarto website:
```shell:
_quarto/
!_quarto/_freeze/
```

Given this expression, `_quarto/_freeze/` is still git-ignored. I think the correct expression is
```shell
_quarto/*
!_quarto/_freeze/
```

**Comment by vincentarelbundock** [comment]
I think we *do* want to ignore the freeze folder. This is not something the typical user will want to keep around. I see freeze as a convenience setting for local website builds.

And users can easily change it manually if they don't want that default.

Am I misunderstanding what you mean?

**Comment by kazuyanagimoto** [comment]
I think freeze is also expected to use for GHA building, which is mentioned in the [Quarto document](https://quarto.org/docs/publishing/github-pages.html#github-action). It allows us to build notebooks includes a long computations, local data, and api secretes through GHA.

My expected behavior is by default, `altdoc` adds `_quarto/*` in `.gitignore` and I can manually add `!_quarto/_freeze/` to keep the freeze files.

The problem is whenever I run `render_docs(freeze = TRUE)`, which add `_quarto/`, as a result, the `.gitignore` will be

```shell
_quarto/*
!_quarto/_freeze/
_quarto/
```

It git-ignores `_quarto/_freeze/`, and I have to manually remove `_quarto/` for each commit.

**Comment by kylebutts** [comment]
Hi @vincentarelbundock, I had that as a mental note to check with you about; but then I forgot. I agree it should be done once in setup_docs. I also changed it to `_quarto/*`

**Comment by vincentarelbundock** [comment]
@kazuyanagimoto the change is merged in the dev version of `altdoc`. You should only have to remove the offending line once from `.gitignore`. It will not be re-spawned every time.

Thanks for the report!
