### ISSUE TITLE
altdoc/quarto for python package

### ISSUE THREAD

**Issue by zeileis** [etiennebacher/altdoc#277]
Etienne @etiennebacher & Vincent @vincentarelbundock, I recently started adopting `altdoc` for my own R packages and have to say I very much like it, well done!

I also have a Python package (together with @retostauffer) for which we would like to build a package web page with the documentation from the package's docstrings. Are you aware of an `altdoc`-like tool that extracts the package information/documentation and sets up a `quarto_website`?

**Comment by etiennebacher** [comment]
Hi @zeileis, I'm glad you like it. I remember something similar was brought up in an issue on the [`r2readthedocs`](https://github.com/ropenscilabs/r2readthedocs/issues/13) repo. Apparently the person who created the issue made a package to generate a Quarto website for python and R docs: https://github.com/zmeers/pyrdocs

However, I have no idea if this works well (I just discovered it today and I don't make python packages). There's also [`quartodoc`](https://machow.github.io/quartodoc/get-started/overview.html) that might correspond more to what you want

**Comment by zeileis** [comment]
Thanks, Etienne, very much appreciated. We'll take a look!

I will close the issue here now. If we have something useful to report based on our experiences we can still comment later.
