### ISSUE TITLE
GH Action build fails for Quarto

### ISSUE THREAD

**Issue by roaldarbol** [etiennebacher/altdoc#285]
I'm attempting to build the docs with GH Pages, and following the documentation, but the build fails. I can't figure out exactly what is happening, but it's related the the `altdoc` action. I'm using the `quarto_website` tool. Could anyone help me debug - is it an issue with the action or something in my repo? [Here's the log](https://github.com/roaldarbol/rpix/actions/runs/10048218755/job/27771710689). The docs renders well locally with `preview_docs()` by the way.

**Comment by etiennebacher** [comment]
I can reproduce with altdoc 0.3.0 but not with the development version. Can you add the following in your DESCRIPTION and let us know if it works?

```
Remotes:
    etiennebacher/altdoc
```

**Comment by roaldarbol** [comment]
Thanks for the swift reply! And YES, that did it! 😃

**Comment by etiennebacher** [comment]
Btw, I just released 0.4.0, you'll be able to remove the Remotes field in a few days
