### ISSUE TITLE
Error on Github actions found for quarto

### ISSUE THREAD

**Issue by joshuafayallen** [etiennebacher/altdoc#294]
Hi all I am currently trying to build my site via github actions. I get an error that `File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/v4/lib/main.js'`. The output repository [can be found here](https://github.com/joshuafayallen/executivestatements/actions/runs/11075716462/job/30777269382). I was hoping y'all could help me out with this.

**Comment by etiennebacher** [comment]
Hi, I think this comes from the Github action that is used to deploy github pages: https://github.com/JamesIves/github-pages-deploy-action/issues/1697

We can't do much on our side, but someone put a workaround there.

**Comment by joshuafayallen** [comment]
Awesome thank you so much!
