### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#64]
Would you let me try to reduce the number of dependencies?

Some of the could be Suggests with a conditional check. Others are called only once or twice and could easily be executed in base R.

**Comment by etiennebacher** [comment]
Absolutely, go ahead.

I just want to point out that this is supposed to be a package for development so I don't think it matters too much if there are many dependencies since it should be installed in a single CI workflow. But if it's not too much work it's always better to have less deps

**Comment by etiennebacher** [comment]
Just out of curiosity, which dependencies do you think could be easily replaced? `jsonlite` is used only once but is so convenient and light that I don't think it's worth removing, and many other packages are installed by other deps anyway (like `cli` or `desc`)
