### ISSUE TITLE
Support `NEWS.Rd`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#65]
This used to be standard.

**Comment by etiennebacher** [comment]
First time I see this. Just for my curiosity do you know some examples of packages that still use this format?

**Comment by vincentarelbundock** [comment]
This was pointed to me by @eddelbuettel. Maybe he has some examples of this and other R conventions could potentially support.

**Comment by vincentarelbundock** [comment]
For later reference:

https://eddelbuettel.github.io/r2u/changelog/
https://eddelbuettel.github.io/anytime/news/
https://eddelbuettel.github.io/anytime/changelog/

I don't have time to look at this in detail now, but will in the future.

**Comment by eddelbuettel** [comment]
> First time I see this. 

Not really, see e.g. https://github.com/lme4/lme4/blob/master/inst/NEWS.Rd as well as WRE :)

>    Things you might like to add to ‘inst’ are a ‘CITATION’ file for use
by the ‘citation’ function, and a ‘NEWS.Rd’ file for use by the ‘news’
function.  See its help page for the specific format restrictions of the
‘NEWS.Rd’ file.
