### ISSUE TITLE
Automatically create a GHA workflow

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/altdoc#66]
A bit more long term but when `altdoc` is more robust and #47 is solved, it would be nice to have a function to make a GHA workflow for `altdoc`, sort of `usethis::use_github_action("pkgdown")`

**Comment by vincentarelbundock** [comment]
I love the idea of using r2u.

FYI, Dirk also has an ultra cool bash script that handles all the deployment and hooks really well into r2u. I find this approach much more transparent and understandable than calling a bunch of separate GitHub actions.

See an example here: https://github.com/vincentarelbundock/marginaleffects/blob/main/.github/workflows/check.yaml

**Comment by etiennebacher** [comment]
Oh yes I use this as well in `tidypolars` (I copied your yaml actually ;) ), it's super fast
