### ISSUE TITLE
Simplify paths

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#70]
I notice that a lot of the code complexity in the package comes from figuring out relative and absolute paths. `altdoc` could be simplified considerably by constraining the user to run the main functions from the root of their package. I don't really see a case where it makes much difference for the user to do:

```r
use_docute("~/blahblah/project")
```

instead of 

```r
setwd("~/blahblah/project")
use_docute()
```

But it makes a big difference for us, because `altdoc` is more complicated than it needs to be.

Therefore, I propose:

1. Remove the `path` argument from all user-facing functions.
2. All user-facing functions call `.assert_dir_is_package()` at the top to enforce the requirement to run in root.

```r
.assert_dir_is_package <- function() {
  flag <- .dir_is_package(getwd())
  if (!isTRUE(flag)) {
    stop("This function must be called from the root of an R package directory.", call. = FALSE)
  }
} 
```

Thoughts?

**Comment by etiennebacher** [comment]
FYI I started without this path complexity and then got an advice to include it in https://github.com/etiennebacher/altdoc/issues/21

A simplification of the path handling while keeping the same robustness would be nice

**Comment by etiennebacher** [comment]
Also there is already a `altdoc:::.check_is_package()` that might be enhanced with the code you proposed

**Comment by vincentarelbundock** [comment]
Hmm, that's interesting. The post isn't super explicit on why it "may fail". If the default truly was just `getwd()`, the obviously things may fail if the user runs outside the package root. But as long as the assertion function is solid and we are sure to run in root of a package, then I don't see a problem. The only possible case would seem to be if the user wants to build a package from the root of a different package, but that seems far-fetched...

Cool, I'll take a look at `check_is_package()`.

**Comment by vincentarelbundock** [comment]
OK, I started doing that, and it would be a lot more work than I anticipated. Also, it feels dumb to do a ton of work to *remove* functionality that is already there and works fine.

So I'll close this.

Thanks for your patience and openness, and sorry for the deluge of issues.

**Comment by etiennebacher** [comment]
No worries, I'm glad you got interested in this package otherwise it would have probably stayed as-is for quite some time
