### ISSUE TITLE
`preview=FALSE` by default

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#71]
I think preview should be FALSE by default, because it is an "invasive" option (opening a new window), and because it doesn't work on some setups (like mine). If we move in that direction, servr and rstudioapi can be Suggests and we can prompt users to install them. FWIW, I never use altdoc::preview() myself, because I don't use Rstudio and I just run the built-in webserver extension of vscode.

Thoughts?

**Comment by etiennebacher** [comment]
What about `preview = rstudioapi::isAvailable()` to know if the user is in an RStudio session? That should return `FALSE` in your case, right?

**Comment by vincentarelbundock** [comment]
My view is: I don't have that package installed globally and never use it locally. And I really think that "build" and "preview" are conceptually distinct operations which should be run in different functions (or at least requested explicitly).

But obviously, this is not a very big deal, and this is your package, so I'm happy to do whatever you prefer.

**Comment by vincentarelbundock** [comment]
(One place where this is well illustrated is when running the tests interactively, which opens a billion preview windows.)

**Comment by etiennebacher** [comment]
> (One place where this is well illustrated is when running the tests interactively, which opens a billion preview windows.)

Ah right, I'm fine with setting as `FALSE` by default

**Comment by vincentarelbundock** [comment]
Cool! We can also do:

```r
preview = getOption(altdoc_preview, default = FALSE)
```

So a user who always wants the preview automatically could set a global option in their `.Rprofile`.

**Comment by etiennebacher** [comment]
Yes, sounds good like this, + it's already what you implemented, right? (except the default is `TRUE`)

**Comment by vincentarelbundock** [comment]
Fixed here: d5c1bc94f40
