### ISSUE TITLE
`update_docs`: `verbose` argument

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#72]
Currently, we silence the output of Rmd or Quarto rendering. But sometimes it is useful to see it when the vignette rendering breaks. We may consider adding a `verbose` argument.

**Comment by etiennebacher** [comment]
Agreed, but presumably we only want the messages when the rendering failed. We could print the messages in the `error` part of `tryCatch()` only and not for all vignettes

**Comment by vincentarelbundock** [comment]
Yep, agreed: only when it fails.

I might also be worth printing the whole thing with `capture.output()` because it shows chunk-level failures, so it's easier to know that a long document fails on the code chunk at line 1345, for ex.

**Comment by etiennebacher** [comment]
Would it make sense to require user interaction to display error messages? For example you have around 25 vignettes in `marginaleffects`. If only 3-4 fail, then the output in the console would be very long and probably hard to read. Maybe we could store the messages for each failure in a separate file (maybe a temporary one), and have a function `show_vignette_failure()` where you could select which vignette failure you want to print in the console, like `show_vignette_failure("vignette_A")`.

That would only be the case in interactive mode, printing all messages at once would be required in GHA for example. Not sure this is a good idea, what do you think?

**Comment by vincentarelbundock** [comment]
Interesting. Will think about this. This feels low priority for now, but it's good to have an issue and think.

**Comment by etiennebacher** [comment]
Any mechanism that hides messages / errors should probably be deactivated automatically in CI, since we usually want to have all available info for debugging
