### ISSUE TITLE
FYI on PR reviews

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#74]
@etiennebacher This is just a point of information.

@rempsyc is moving on to bigger and better things and our collaboration is coming to an end.

I will keep making PRs, but he probably won't be there to review or merge.

**Comment by etiennebacher** [comment]
Ok, thanks for the heads-up. I can try to review a few but there should be some option to merge small PRs on your own. When you open a PR, do you have a checkbox to merge without the review requirements or is it only me?

**Comment by vincentarelbundock** [comment]
No, unfortunately I think the override is only for owners.

If you change the settings I can be extra careful about merging minor fixes and wait for any feature or behavior change.

Your call, obviously.

**Comment by etiennebacher** [comment]
I changed the settings to remove the mandatory review and approval. I'm not sure how much I'll be able to review the changes (maybe skim through them but can't check in detail), so I don't want to block you with this. 

Can you ping me for important and/or user-visible changes? In any case such changes should be discussed in issues before opening a PR (as is currently the case)
