### ISSUE TITLE
Improve `altdoc` README

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#75]
This issue is intended to collect ideas for improvements to the `altdoc` README and tutorial. This is long term:

+ [x] Recommended strategy for deployment on Github via the `docs/` folder.
+ [x] List of `$ALTDOC` variables
+ [ ] Include images in both the vignettes and the README to illustrate static files locations.

**Comment by etiennebacher** [comment]
FYI I'm not a big fan of super long README. If it becomes too long I'd rather have links to the documentation where we have plenty of space to explain things

**Comment by vincentarelbundock** [comment]
noted
