### ISSUE TITLE
Generation of Code of Conduct and Changelog

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#76]
This is listed as a feature:

> automatically generate Changelog and Code of Conduct sections

I would argue that this should *not* be a feature of `altdoc`. In my view, a documentation generator should take the existing documentation and turn that into a website. If there is a code of conduct, then that should be displayed on the website. If there is no code of conduct, then it should not be displayed.

There are many packages to help people prepare packages: `devtools`, `usethis`, `pkgKitten`. We should let users create their package and then handle documentation processing and rendering.

Thoughts?

**Comment by etiennebacher** [comment]
AFAIR `altdoc` doesn't create these files, it creates the sections in the docs. For example if there's a LICENSE, it will be displayed in the docs (like on `altdoc` website) but it won't create it if it doesn't exist. If it does, that's a mistake indeed

**Comment by vincentarelbundock** [comment]
ooops, sorry about that you're totally right. I mis-remembered something i saw in the test files, where you (appropriately) create code of conducts to test.
