### ISSUE TITLE
Deprecate `custom_reference`

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#77]
As far as I can tell, this is a path to external script and the only thing we do internally is `source(custom_reference)`.

I don't understand what is the benefit of that. It is literally just an external script, so users might as well just run that script independently script at the end to modify the files. For example, the `polars` team could execute another script from their `Makefile`.

Another problem is that it is "opaque". It's not clear to users *exactly* when the script will be sourced. If they run a script *after* everything is done, then they can have a better idea of the state of the repository. This is especially problematic in the case of `altdoc` since we support several different output formats, which may be in different states until the end (think of `mkdocs` which renders in a different location).

So I think it's safer to run external scripts at the very end when the state is known and observable.

Also, it clutters the user interface with an argument that does is not actually acted upon by `altdoc` functions.

Instead of this, I propose a vignette which illustrates how to use external scripts in a website build workflow.

**Comment by etiennebacher** [comment]
This was mostly a quick patch to build the reference section of `polars` with our own script. Agreed it should be removed in the end if we have a nice alternative
