### ISSUE TITLE
Themes vignette

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#79]
Show minimal examples in all document generators to customize the look of the website with themes or CSS

**Comment by etiennebacher** [comment]
Or should we just redirect users towards the appropriate sections in the documentation of each tool? Each documentation generator has different CSS classes so it might be overkill to provide examples for each

**Comment by vincentarelbundock** [comment]
https://github.com/etiennebacher/altdoc/pull/95
