### ISSUE TITLE
Deprecate `theme` argument?

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#81]
The `theme` argument only works in `mkdocs`. Do we want to deprecate this?

It feels like we should promote a single workflow for all generators, and that the recommended customization strategy should be to edit the files manually in `altdoc`.

Otherwise, we might have infinite requests for new arguments to modify CSS and such. And it is trivial to add a line for `material` in the `mkdocs.yml` manually. That's the beauty of the new system...

**Comment by etiennebacher** [comment]
Yup, agreed, there's no point in having this argument inconsistency anymore
