### ISSUE TITLE
docsify: Sidebar displays locally but not on Github Pages for countrycode repo

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#84]
Look into this after PR merge. It works locally, so I'm not sure what the problem is.

**Comment by etiennebacher** [comment]
Do you have a fork that shows this? I see that `countrycode` uses docute but not docsify

**Comment by vincentarelbundock** [comment]
Here's an example: https://vincentarelbundock.github.io/WDI/

I added you as collaborator to the `WDI` repo in case you want to push new commits to try variations in the docs...

**Comment by etiennebacher** [comment]
Might require a `.nojekyll` file: https://docsify.js.org/#/more-pages?id=sidebar

**Comment by vincentarelbundock** [comment]
yep, thanks!
