### ISSUE TITLE
Support HTML output

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#85]
> some Rd files fail because they produce an HTML output and quarto throws an error: Functions that produce HTML output found in document targeting markdown_strict [CUT]. This is the case of coef_rename.Rd in modelsummary. Looks like the issue is that modelsummary doesn't know we want a markdown output when we use quarto::render() (but it works when we specify format: gfm in the header so might an upstream issue with quarto)

This is almost certainly a problem with the current `altdoc` too, so I'm transferring this out of the big PR for later implementation.

Packages like `modelsummary` will be difficult to support given the `md` target, but I think it's possible, I want to use this in all my packages, and I'll work on it eventually.

**Comment by etiennebacher** [comment]
> I want to use this in all my packages, and I'll work on it eventually.

May I ask why? I mean I'm very happy that you're interested in this package and making all these efforts, but the websites for WDI, countrycode and modelsummary are already very nice.

`altdoc` can be better for some packages like polars or marginaleffects that have specific needs, but pkgdown is very robust and battle-tested so I'm just wondering why you'd prefer altdoc for more classic packages

**Comment by vincentarelbundock** [comment]
Mostly because I want to [dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) `altdoc` and because I don't find the `pkgdown` look especially pretty.

This is a hobby  and I'm doing this for fun ;)

**Comment by vincentarelbundock** [comment]
Note to self: Maybe this gets us closer, but the tables do not look like they *quite* work:

```yaml
format:
  md:
    prefer-html: true
```

**Comment by vincentarelbundock** [comment]
@etiennebacher Fancy HTML output generated by R functions like `modelsummary`, `kableExtra` and `gt` mostly works when the code from the previous post is insert in a Quarto YAML preamble. Without that, then the table will mostly not work, or it will work only in packages like `modelsummary` which default to markdown tables when there is no other "table factory" available.

What do you think we should do? On the one hand, users can insert this easily in their vignettes, we can document it in a FAQ, and I really dislike the idea of modifying YAML on the fly. On the other, if we don't insert it automatically, then `gt` tables and such will not work in man pages.

Thoughts?

**Comment by etiennebacher** [comment]
How about something like `options(altdoc_prefer_html_in_man, altdoc_prefer_html_in_vignettes)` with both `TRUE` by default? (names can change ofc)

That way, we don't clutter the functions with niche arguments but users can still opt-out if they want

**Comment by etiennebacher** [comment]
In any case users must have a way to enable HTML rendering in `man` pages, and that requires either a function option or a package option

**Comment by vincentarelbundock** [comment]
You're probably right. But arrrrrgh, I really didn't want to bring back `.modify_yaml` and friends. Feels like such a hack!

If we can avoid global options, I think it's better to have an actual argument for that.

**Comment by etiennebacher** [comment]
> If we can avoid global options, I think it's better to have an actual argument for that.

I think it's the first time I see you prefer function arguments ^^ Why do you prefer them over global options in this case? It seems to me that only a handful of package developers output some HTML, so it feels weird to expose function arguments to everyone

**Comment by vincentarelbundock** [comment]
Haha, I should try to get rid of this reputation. 

In general, my understanding is that global options are strongly discouraged in R package development. In my own packages, I try (but often fail) to use global options when it is necessary to modify the behavior of an existing argument, but not to control independent functionality.

`modelsummary` is [a pretty bad counter example](https://modelsummary.com/reference/datasummary.html?q=global%20option#global-options), but there are sooo many possible options there that it would make the API completely unreadable.

But yeah, this is probably a case of "do what I say, not what I do".

**Comment by etiennebacher** [comment]
I see your point, my view was more like this is an argument that will only be useful to a few package developers so it should be available via a "hidden" option. 

I don't have a strong point of view on this, we can add it as an arg, maybe `prefer_html = c("all", "man", "vignettes", "none")`?

**Comment by vincentarelbundock** [comment]
Cool, I'll think about it. I can't really think of a case where it would be **bad** to include this, because the ultimate format is web/html. So perhaps it makes sense to make it a little harder to *disable*.

Will think on it and propose a PR soon.

**Comment by vincentarelbundock** [comment]
OK, here's what I think is possibly a good idea: `setup_docs()` creates four new files:

* `altdoc/preamble_man_qmd.yml`
* `altdoc/preamble_vignettes_qmd.yml`
* * `altdoc/preamble_man_rmd.yml`
* `altdoc/preamble_vignettes_rmd.yml`

If there is no preamble in the user-created file, then we stick this at the top. If there is a preamble, we respect user choice and don't paste anything. That way, if someone wants to customize the preamble of a specific vignette, they can override our defaults easily.

**Comment by etiennebacher** [comment]
Vignettes can be Rmd or qmd but man pages can only be qmd since we do the conversion, right?

**Comment by vincentarelbundock** [comment]
Yep, you're right
