### ISSUE TITLE
Post-processing vignette (for `polars` and others)

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#87]

**Comment by vincentarelbundock** [comment]
Note to self: My original plan was to just run a script after the full website rendering. This is likely to work in Docsify and Docute, but probably not in MkDocs, because when we call `mkdocs build -q`, it creates a bunch of hardcoded files (ex: search and links) for what is at that moment held in `mkdocs.yml`. So we need to modify the settings file in the middle of `render_docs()` instead of after.

Probably this means reinstating something like `custom_reference`, but of more general applicability.

I am annoyed.

**Comment by vincentarelbundock** [comment]
Alternatively, we could use a *pre-processing* step to modify `altdoc/mkdocs.yml` (and then restore it).

**Comment by etiennebacher** [comment]
> Probably this means reinstating something like custom_reference, but of more general applicability.

Or we could store custom scripts in `altdoc` with a special name like `_altdoc_extension_1.R`. Then in `render_docs()` we check whether files with such a name exist, and if there are some then we source them. That way there's no need for an extra argument in `render_docs()`.

**Comment by vincentarelbundock** [comment]
Yep, I was thinking about that, but maybe that's overengineered. IIRC, in the current `polars` website we have a file called `mkdocs_orig.yml` (or somesuch), which we modify and copy to `mkdocs.yml`. We can just store that original file in `altdoc/`, run a script manually to modify and copy it to `altdoc/mkdocs.yml`, and then run `render_docs()`:

```r
source("altdoc/customize_navbar.R")
altdoc::render_docs()
```


That's essentially zero change to the current workflow and doesn't require us to have hard to understand hidden processes that we would need to document.

**Comment by etiennebacher** [comment]
`mkdocs_orig.yml` is not the problem, this can replaced by the template in the `altdoc/` folder. The problem is `docs/make-docs.R` where we customize the structure of the "Reference" page and the names of each man page. At what point of the altdoc workflow should this be run? 

I'll try to find some time this week to explore this more.

**Comment by vincentarelbundock** [comment]
Users could look at `man/*.Rd` files to create the index.
