### ISSUE TITLE
Freeze functionality

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#92]
Separate issue to discuss design for a freeze functionality.

Benefit:

* Very large websites are very time consuming to consume

Cons:

* The maintainer may not notice if vignettes are broken.
* Website may become out of sync with package.

Design:

* Given the cons above, this should be `FALSE` by default.
* I don't have a clear design in mind yet, but we could store the `.qmd` and `.Rmd` files somewhere and then compare them to the new ones. If the original source files have not changed, then we don't need to render them.

**Comment by etiennebacher** [comment]
In principle, I'm fine with this functionality when it comes to being able to apply changes locally and quickly see if the website is as expected. If the user sets `freeze = TRUE`, then a clear message must be printed in the console about this. 

However, this feature should be always be disabled in CI.

Design ideas:

1. when vignettes are rendered, store their last date of modification with `fs::file_info()` in `altdoc/`
2. if `freeze = TRUE`, compare the dates of last modif of vignettes in `vignettes/` with the dates stored in `altdoc`. If dates are the same, do not render

**Comment by vincentarelbundock** [comment]
Interesting idea. I wonder if there's a risk with different clones of the repo on different computers.

Another option might be to have an `altdoc/_freeze` directory which would be in `.gitignore` by default, and hold copies of the `.qmd` and `.Rmd` files. Those are plain text, so take no space locally (and are not committed to the repo). Then we can compare the actual files line by line quickly, or compare hashes to see if they changed.

In any case, I'll play with different ideas when I find time and propose a draft PR you can comment on.

**Comment by etiennebacher** [comment]
FYI for `R/altdoc_variables.R` (modified by you 3 days ago) gives the correct modification date:

```r
fs::file_info("R/altdoc_variables.R")$modification_time
#> [1] "2023-11-17 13:51:11 CET"
```
but maybe that value changes depending on time zones, can you try?
